#!/usr/bin/env python3

from pathlib import Path
from urllib.parse import urlencode

USERNAME = "RichithaaReddy"
README_PATH = Path(__file__).resolve().parents[1] / "README.md"

TECH_STACK = (
    ("CSS3", "1572B6", "css3", "white"),
    ("C", "00599C", "c", "white"),
    ("R", "276DC3", "r", "white"),
    ("Java", "ED8B00", "openjdk", "white"),
    ("HTML5", "E34F26", "html5", "white"),
    ("Vercel", "000000", "vercel", "white"),
    ("Oracle", "F80000", "oracle", "white"),
    ("Anaconda", "44A833", "anaconda", "white"),
    ("Bootstrap", "8511FA", "bootstrap", "white"),
    ("Django", "092E20", "django", "white"),
    ("React", "20232A", "react", "61DAFB"),
    ("React Native", "20232A", "react", "61DAFB"),
    ("React Router", "CA4245", "react-router", "white"),
    ("React Hook Form", "EC5990", "reacthookform", "white"),
    ("Redux", "593D88", "redux", "white"),
    ("Streamlit", "FE4B4B", "streamlit", "white"),
    ("Apache Tomcat", "F8DC75", "apache-tomcat", "black"),
    ("Pandas", "150458", "pandas", "white"),
    ("PyTorch", "EE4C2C", "pytorch", "white"),
    ("scikit-learn", "F7931E", "scikit-learn", "white"),
    ("MLflow", "D9EAD3", "numpy", "blue"),
    ("NumPy", "013243", "numpy", "white"),
    ("Matplotlib", "FFFFFF", "matplotlib", "black"),
    ("Keras", "D00000", "keras", "white"),
    ("GitHub Actions", "2671E5", "githubactions", "white"),
    ("Git", "F05033", "git", "white"),
)


def image(alt: str, url: str) -> str:
    return f"![{alt}]({url})"


def url_with_query(base_url: str, **parameters: object) -> str:
    return f"{base_url}?{urlencode(parameters)}"


def badge(
    label: str,
    color: str,
    logo: str,
    logo_color: str,
) -> str:
    badge_label = label.replace("-", "--").replace(" ", "_")
    url = url_with_query(
        f"https://img.shields.io/badge/{badge_label}-{color}.svg",
        style="for-the-badge",
        logo=logo,
        logoColor=logo_color,
    )
    return image(label, url)


def stats_card(path: str = "api", **parameters: object) -> str:
    return image(
        "GitHub statistics",
        url_with_query(
            f"https://github-readme-stats.vercel.app/{path}",
            username=USERNAME,
            theme="rose",
            hide_border="false",
            **parameters,
        ),
    )


def render_readme() -> str:
    stack = "\n".join(badge(*technology) for technology in TECH_STACK)
    stats = "\n".join(
        (
            f"{stats_card(include_all_commits='true', count_private='true')}<br/>",
            image(
                "GitHub contribution streak",
                url_with_query(
                    "https://nirzak-streak-stats.vercel.app/",
                    user=USERNAME,
                    theme="rose",
                    hide_border="false",
                ),
            )
            + "<br/>",
            stats_card(
                "api/top-langs/",
                include_all_commits="true",
                count_private="true",
                layout="compact",
            ),
        )
    )

    return f"""<!-- Generated by scripts/render_readme.py. -->
# Hello

I am a Data Science enthusiast with experience in machine learning, EDA, and predictive modeling. Skilled in Python, SQL, and building end-to-end data-driven applications using React and Django. Passionate about turning data into actionable insights and real-world solutions.

# 💻 Tech Stack:

{stack}

# 📊 GitHub Stats:

{stats}

### ✍️

{image("Quote", url_with_query("https://quotes-github-readme.vercel.app/api", type="horizontal", theme="radical"))}

### 🔝 Top Contributed Repo

{image("Top contributed repositories", url_with_query("https://github-contributor-stats.vercel.app/api", username=USERNAME, limit=5, theme="dark", combine_all_yearly_contributions="true"))}

---

[![Profile views](https://visitcount.itsvg.in/api?id={USERNAME}&icon=0&color=0)](https://visitcount.itsvg.in)

<!-- Proudly created with GPRM ( https://gprm.itsvg.in ) -->
"""


def main() -> None:
    README_PATH.write_text(render_readme(), encoding="utf-8")


if __name__ == "__main__":
    main()
